[build]
# Number of parallel jobs, defaults to # of CPUs
jobs = 8

[target.x86_64-unknown-linux-gnu]
# Use mold linker for faster builds on Linux
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[term]
# Enable colored output
color = "always"

[alias]
# Useful aliases
t = "test"
tc = "test --all-features -- --nocapture"
cov = "llvm-cov --all-features --workspace --html"
ci = "clippy -- -D warnings"
tq = "test -- --quiet"
tn = "test -- --nocapture --test-threads=1"

[env]
# Set test threads to prevent flaky tests
RUST_TEST_THREADS = "4"
# Better backtraces
RUST_BACKTRACE = "1"

[profile.test-coverage]
inherits = "test"
# Better coverage data
opt-level = 0
overflow-checks = false
debug = true
debug-assertions = true
codegen-units = 1
lto = false
incremental = false

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1